
[package]
name = "rust_firewall"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.1"
serde = { version = "1.0", features = ["derive"] }
rocket_dyn_templates = { version = "0.1", features = ["tera"] }
rust-iptables = "0.0.2"
